### ISSUE TITLE
The 'main' parameter in plotXYresiduals() is not responding

### ISSUE THREAD

**Issue by TYMichaelsen** [svkucheryavski/mdatools#100]
Hi Sergey,

While using the PLS features of mdatools (version 0.11.5) I noticed that the argument for setting a custom title using the plotXYResiduals() function is not responding. 

MRE:
```
X = matrix(rnorm(100 * 10), 100, 10)
Y = matrix(rnorm(100 * 10), 100, 10)
library(mdatools)
m <- pls(X, Y, 10,cv = 1)

plotXYResiduals(m)
plotXYResiduals(m,main = "A title") # The title does not change.
```

Best,
Thomas

**Comment by svkucheryavski** [comment]
closed in 0.12.0 - coming soon.
