### ISSUE TITLE
functions missing?

### ISSUE THREAD

**Issue by czanetti** [svkucheryavski/mdatools#101]
Hello,
 I just wanted to notify that there are some functions in the package help not present in the library. (e.g.  a bunch of summary functions). Is this an issue just for myself?

C
![immagine](https://user-images.githubusercontent.com/58081557/143418704-0a7723fd-5277-4d8f-b303-56502333e9d3.png)

**Comment by svkucheryavski** [comment]
They are all present but implicitly. It is just the way R works. When you write `summary(m)` where `m` is a PLS model, R will automatically call `summary.pls` function instead. But when `m` is PCA model, R will call `summary.pca()`. For a user all this internal "kitchen" is hidden, so you do not care and can re-use the same functions for different objects.

Any R package has a lot of extra functions, which users should not use directly.

**Comment by czanetti** [comment]
thanks for the clarification! 

I was a bit confused because i was looking for a function that would output regression coefficients in a similar way to functions for selectivity ratios or VIP scores.
I tried using `getRegcoeffs(m)` or `summary.regcoeffs(m)`  but with no chance.
I ended up using the summary
`summary(m$coeffs, ncomp=5)`

This makes more sense now, Thanks!
C

**Comment by svkucheryavski** [comment]
I ok, I see it can be a bit confusion indeed. I would recommend to use the tutorial, it covers most of the aspects like this. For example if you open this: https://mda.tools/docs/pls--models-and-results.html and scroll a bit down, it has a section about regression coefficients and how to investigate them (here is a direct link https://mda.tools/docs/pls--models-and-results.html#regression-coefficients)
