### ISSUE TITLE
simcam 3D graph

### ISSUE THREAD

**Issue by chris-santos** [svkucheryavski/mdatools#102]
- Hi, I am trying to visualize the results of simcam of a dataset with 5 factors, and it would be great if it was possible to generate a **plot in 3D**, or if we could have the dataframe with the data points to handle it.

I am being able to generate 4 graphs like this to see how each factor behaves in relation to each other:
```
plotCooman(res_mm, c(1, 2) ) #c(1,2) = fator1 x fator2:
plotCooman(res_mm, c(1, 3)) #
plotCooman(res_mm, c(1, 4)) # 
plotCooman(res_mm, c(1, 5))
```
so, perhaps there´s another way I could visualize this in 3D, not sure

**Comment by svkucheryavski** [comment]
You can not make Cooman plot for different factors. The overall idea of "simcam" is to combine together several SIMCA models, which are already properly validated and optimised, so every model has its own number of optimal components. When you run:

plotCooman(n, c(1, 2))

The values 1 and 2 are not factors, they are models. This means make a Cooman plot for first and second models in your simcam object.
