### ISSUE TITLE
Not working with rmarkdown

### ISSUE THREAD

**Issue by GregChojecki** [svkucheryavski/mdatools#110]
Hi Sergey,

 I hope you are doing well.

I love your package, it helped me many times while pre-processing NIR spectra.

One issue though: rmarkdown does not like it. I had to pre-process my spectra, save them and then only my document could be knitted at all.

If possible, please improve. 

Have a good day,
Greg Chojecki

**Comment by svkucheryavski** [comment]
Hi Greg,

thanks for your kind feedback. Can you please give more details on this issue? I use mdatools with RMarkdown every day and never experienced any problem. Actually the tutorial (https://mda.tools/docs/index.html) is fully written in RMarkdown. Perhaps you can make a small example which I can reproduce on my side in order to see the problem? Thanks.

With best wishes
Sergey

**Comment by GregChojecki** [comment]
Hi Sergey,
Thank you for your quick reply.
You are right, it is not markdown. It is how mdatools interact with caret's plsda.
mdatools masks caret's plsda. I wanted to use mdatools for spectra pre-processing, then use caret. Unfortunately, the problem is I am not able to detach mdatools.
Please run:
            ## Start            library(caret)            pls.no.mdatools <- train(Species~., data=iris, method="pls"); pls.no.mdatools            caret::confusionMatrix(predict(pls.no.mdatools, iris),iris$Species)

             library(mdatools)            detach("package:mdatools", unload = TRUE)              # pacman::p_unload(mdatools) # I tried pacman as well            library(caret)            pls.detached.mdatools <- train(Species~., data=iris, method="pls")
            ## End---
For a reason mdatools somehow cannot be fully detached.
Is there a method to detach mdatools or I need to restart RStudio each time I want to use caret's plsda?
Best regards,Greg

    On Thursday, 24 November 2022 at 09:22:00 GMT, Sergey Kucheryavskiy ***@***.***> wrote:  
 
 


Hi Greg,

thanks for your kind feedback. Can you please give more details on this issue? I use mdatools with RMarkdown every day and never experienced any problem. Actually the tutorial (https://mda.tools/docs/index.html) is fully written in RMarkdown. Perhaps you can make a small example which I can reproduce on my side in order to see the problem? Thanks.

With best wishes
Sergey

**Comment by svkucheryavski** [comment]
There is nothing special in mdatools which prevents the methods from the package from detaching. But there is a simple workaround. Instead of attaching the package before using some methods:

```r
library(mdatools)
X = prep.norm(X, type = "length")
```

You can do the following:

```r
X = mdatools::prep.norm(X, type = "length")
```

I believe it will solve this problem.
