### ISSUE TITLE
Citing your package

### ISSUE THREAD

**Issue by EOMAK91** [svkucheryavski/mdatools#115]
Hi there,

Thanks for the R package, I used it for centering and scaling my lipidomics data and wanted to cite the package when I publish. Do you have a recommended citation you'd like me to use?

**Comment by svkucheryavski** [comment]
Hi, you can cite the package as follows: Sergey Kucheryavskiy, mdatools – R package for chemometrics, Chemometrics and Intelligent Laboratory Systems, Volume 198, 2020 (DOI: [10.1016/j.chemolab.2020.103937](https://doi.org/10.1016/j.chemolab.2020.103937)).

Thank you in advance.
