### ISSUE TITLE
prep.autoscale does not work well with negative data

### ISSUE THREAD

**Issue by Garrus990** [svkucheryavski/mdatools#59]
Hi Sergey,

thank you for the awesome work you do with `mdatools`. I would like to draw your attention to one detail that I've managed to find when I was working with your package. Let's assume that you have a matrix whose one column has a negative mean. In such a case, the `prep.autoscale` function wrongly standardizes values. When you check if the variability of a column is "small enough" (by comparing it to `max.cov` parameter) you obtain a negative value if you divide such a negative mean by by-definition positive standard deviation. Shouldn't you take `abs(center)` to avoid such a behavior? In the current implementation even massively variable features will not be scaled if their mean is negative.

Cheers,
Szymon

**Comment by svkucheryavski** [comment]
Hi Szymon,

thanks a lot, indeed this is a bug. Will fix it asap.
