### ISSUE TITLE
PLS-DA: Use different component counts for groups

### ISSUE THREAD

**Issue by Thosty** [svkucheryavski/mdatools#93]
I created a PLS-DA model for a variable with three groups. Group A gets the best validation results when using 2 components. However Group B and C gets the best results when using 4 components. 

Is it a good idea to select different component counts for groups when predicting new data? Or must be the component count for all groups always the same?

**Comment by svkucheryavski** [comment]
Well, it is difficult to say anything specific without working with the data. Using PLS-DA can be tricky if you have more than 2 groups. In general I would advice the following:

1. Make several individual PLS-DA models for each class. In this case you can adjust needed number of components for each group. See reference 1 for some interesting discussion about this and the use of PLS-DA in general.
2. Use hard/soft PLS-DA methods (see ref. 2). They are not directly implemented in *mdatools* but you can write an add-on function if you want.
3. Consider one-class classification, e.g. DD-SIMCA

References:
1. [https://onlinelibrary.wiley.com/doi/abs/10.1002/cem.2609](https://onlinelibrary.wiley.com/doi/abs/10.1002/cem.2609)
2. [https://onlinelibrary.wiley.com/doi/abs/10.1002/cem.3076](https://onlinelibrary.wiley.com/doi/abs/10.1002/cem.3076)

**Comment by Thosty** [comment]
Thank you. Simca is good working for me.
